name: Deploy Frontend

on:
  push:
    branches: [v5.0-dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /opt/qpet/qpet-frontend
            git pull origin v5.0-dev
            cd /opt/qpet
            docker compose build frontend
            docker compose up -d frontend
